### ISSUE TITLE
OpenAI's TTS

### ISSUE THREAD

**Issue by williamzebrowskI** [SagarDangal/audio_chat_with_openAI#1]
@SagarDangal - Really like this. 

Any suggestions on how you'd incorporate this with the OpenAI's TTS API ([here](https://platform.openai.com/docs/guides/text-to-speech?lang=python))

Also, have you tried streaming audio through a websocket?  Or as you have implemented, it may be cool to put the above TTS API on the `voice_frontend.html` for a stream to the user ?

Looking forward to hearing your thoughts.

**Comment by SagarDangal** [comment]
for the OpenAI TTS
speech_file_path = Path(__file__).parent / "speech.mp3"
response = client.audio.speech.create(
  model="tts-1",
  voice="alloy",
  input="Today is a wonderful day to build something people love!"
)

we do not need to use gtts in frontend we can create a speech of 10 sec and passed it to frontend through websocket , and play that audio in frontend.
